### ISSUE TITLE
[Database] Migrate to the new Cloud Firestore

### ISSUE THREAD

**Issue by Chan4077** [Chan4077/StudyBuddy#5]
# Notes
P.S. I've already migrated (successfully :tada:) the webapp to the new Cloud Firestore.

Currently, the app isn't hooked up to any database yet.

# Todos
- [x] Complete data structure
- [x] Setup security rules
- [x] Actually migrate the app to Cloud Firestore

See Chan4077/StudyBuddy-web#1

**Comment by Chan4077** [comment]
This is done, so I'll close it for now.
